apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-container
        image: my-web-app:latest
        imagePullPolicy: Never # Uses the image you built locally
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer # This makes it accessible on your localhost
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000